apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: orsx3srzu-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/orsx3srzu-dotnet-basic-gitops